# configs/iso_config.yaml

pricing:
  default_buy_price: 10.0  
  default_sell_price: 1.0  
  parameters:
    min_price: 1.0
    max_price: 10.0

# Specifies which ISO implementation to use
type: "HourlyPricingISO"

# Parameters specific to the chosen ISO
parameters:
  # For HourlyPricingISO
  hourly_rates:
    0: 4.0
    1: 4.0
    2: 4.0
    3: 4.0
    4: 4.0
    5: 5.0
    6: 6.0
    7: 6.0
    8: 5.5
    9: 5.0
    10: 5.0
    11: 5.5
    12: 6.0
    13: 6.0
    14: 5.5
    15: 5.0
    16: 5.0
    17: 5.5
    18: 6.0
    19: 6.0
    20: 5.5
    21: 5.0
    22: 4.5
    23: 4.0

  # Example: To use RandomPricingISO, change type and parameters accordingly
  # type: "RandomPricingISO"
  # parameters:
  #   min_price: 40.0
  #   max_price: 60.0
